version: '3'

services:

  app:
    image: leonardoaii71/poll-app:beta
    networks:
      - web
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    restart: "no"

  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=polls
    networks:
      - web
    ports:
      - 3306:3306
    restart: always

networks:
  web: