version: '3'

services:

  spring:
    image: leonardoaii71/spring:final
    ports:
      - 8080
    environment:
      - SERVICE_PORTS=8080
      - SERVER_PORT=8080
    networks:
      - web
      - db
    depends_on:
      - mysqldb
      - redis
    deploy:
      replicas: 2

  redis:
    image: redis
    hostname: redis
    networks:
      - web
    ports:
      - 6379:6379

  haproxy:
    image: dockercloud/haproxy:latest
    depends_on:
      - spring
      - spring2
    environment:
      - BALANCE=roundrobin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 1936:1936
      - 443:443
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

  mysqldb:
    image: mysql
    networks:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=polls
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - web

volumes:
  mysql_db:

networks:
  web:
    driver: overlay
  db:

